spring.application.name=demo
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=Defi-Blockchain;encrypt=false
spring.datasource.username=sa
spring.datasource.password=Kha@1205
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.docker.compose.enabled=false
web3j.client-address=https://eth-sepolia.g.alchemy.com/v2/KZNIIMe0fczLJf0VLuLjF