spring.application.name=demo
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=Defi_Blockchain;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.docker.compose.enabled=false
web3j.client-address=https://eth-sepolia.g.alchemy.com/v2/KZNIIMe0fczLJf0VLuLjF

osva.oracle.private-key=0x_XÓA_CHỮ_NÀY_ĐI_VÀ_PASTE_PRIVATE_KEY_VÍ_CỦA_BẠN_VÀO

# Địa chỉ của Contract OSVAPool đã deploy trên Sepolia
osva.pool.address=0xbd2B2030c82DD76bbEe0F361525Ac36b5A6d6484

# ID mạng Sepolia (Chuẩn của giao thức EIP-712 cần domain chainId)
osva.sepolia.chain-id=11155111


# Hibernate Auto-DDL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
